### ISSUE TITLE
What program are these for?

### ISSUE THREAD

**Issue by cstby** [alternateved/kaolin-inspired#1]
I was linked to your project from an emacs blog. Looks like these are not for emacs?

**Comment by alternateved** [comment]
Hello!

Those are the colorschemes ported from [kaolin-themes](https://github.com/ogdenwebb/emacs-kaolin-themes) to other applications like kitty, alacritty, qutebrowser etc., although for kitty terminal those themes are now built in (accessible by `kitty +kitten themes` command).

If you are looking for Emacs kaolin themes, check above link.

Could you by chance sent me a link to that blog? I might contact the author to correct that link to direct others to proper [emacs-kaolin-themes](https://github.com/ogdenwebb/emacs-kaolin-themes).
